# Catppuccin Latte
gui:
 theme:
  activeBorderColor:
    - '#dd7878'
    - bold
  inactiveBorderColor:
    - '#8c8fa1'
  optionsTextColor:
    - '#1e66f5'
  selectedLineBgColor:
    - '#ccd0da'
  cherryPickedCommitBgColor:
    - '#bcc0cc'
  cherryPickedCommitFgColor:
    - '#dd7878'
  unstagedChangesColor:
    - '#d20f39'
  defaultFgColor:
    - '#4c4f69'
  searchingActiveBorderColor:
    - '#df8e1d'

authorColors:
  '*': '#8839ef'
